name: "Update Changelog"

description: "Custom action to update changelog based on input parameters."

inputs:
  pr_data:
    description: "List of ids and PR bodies"
    required: true
  changelog_path:
    description: "The value associated with the type."
    required: true
  base_branch:
    description: "The base branch for the changelog update"
    required: true
  suffix:
    description: "Suffix for the changelog update"
    required: true

runs:
  using: "composite"
  steps:
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.x"

    - name: Install dependencies
      shell: bash
      run: |
        python -m pip install --upgrade pip
        pip install keepachangelog

    - name: Run update_changelog.py
      shell: bash
      run: |
        python ${{ github.action_path }}/update_changelog.py "${{ inputs.pr_data }}" "${{ inputs.changelog_path }}" "${{ inputs.base_branch }}" "${{ inputs.suffix }}"
