name: "Update Changelog"

description: "Custom action to update changelog based on input parameters."

inputs:
  pr_ids:
    description: "The type of update to perform."
    required: true
  changelog_path:
    description: "The value associated with the type."
    required: true

runs:
  using: "composite"
  steps:
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.x"

    - name: Install dependencies
      shell: bash
      run: |
        python -m pip install --upgrade pip
        pip install -r ${{ github.action_path }}/requirements.txt

    - name: Run update_changelog.py
      shell: bash
      run: |
        python ${{ github.action_path }}/update_changelog.py "${{ inputs.pr_ids }}" "${{ inputs.changelog_path }}"
