name: "validate-pr-description"

runs:
  using: "composite"
  steps:
    - name: Save PR body to temporary file
      shell: bash
      run: |
        echo "${{ inputs.pr_body }}" > pr_body.txt

    - name: Run validation script
      shell: bash
      run: |
        python3 validate_pr_description.py pr_body.txt

inputs:
  pr_body:
    description: "The body of the pull request."
    required: true

outputs: {}

files:
  - validate_pr_description.py
