name: Validate PR Description

on:
  pull_request:
    types:
      - opened
      - edited

    branches:
      - main
      - "stable-*"

jobs:
  validate-pr-description:
    runs-on: ubuntu-latest

    steps:
      - name: Use custom PR validation action
        uses: ./actions/documentation/validate-pr-description
        with:
          pr_body: "${{ github.event.pull_request.body }}"

      - name: Set status
        if: failure()
        run: echo "Validation failed."