name: Weekly Changelog Update

on:
  schedule:
    - cron: '0 0 * * 0' # Every Sunday at 00:00
  workflow_dispatch:
env:
  GH_TOKEN: ${{ secrets.YDBOT_TOKEN }}

jobs:
  gather-prs:
    runs-on: ubuntu-latest
    outputs:
      prs: ${{ steps.pr-list.outputs.prs }}
    steps:
      - name: Check out repository
        uses: actions/checkout@v4
        
      - name: Set up date range
        id: date-setup
        run: |
          LAST_WEEK_DATE=$(date -d "7 days ago" '+%Y-%m-%d')
          echo "LAST_WEEK_DATE=$LAST_WEEK_DATE" >> $GITHUB_ENV

      - name: Update changelog for 'main' branch
        run: |
          $(gh workflow run update_changelog.yml -r main -f start=$LAST_WEEK_DATE)

      - name: Run workflow on 'stable-' branches
        run:
          for branch in $(git branch -r | grep 'origin/stable-' | sed 's/origin\///'); do
            echo "Running workflow on $branch"
            gh workflow run update_changelog.yml -f start=$LAST_WEEK_DATE -r $branch
          done
